language: java

jdk:
  - oraclejdk8

script:
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET}

deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '!*datasafe-business*' -F unittests
  - bash <(curl -s https://codecov.io/bash) -f '*datasafe-business*' -F e2e_tests

notifications:
  webhooks:
    urls:
      - https://webhook-proxy-datasafe.cloud.adorsys.de/travis-ci/openshift.adorsys.de/datasafe/datasafe-rest-service
    on_success: always
    on_failure: never
    on_start: never