# Using bash because Travis CI does not support Java on Windows

sudo: required

branches:
  except:
    - gh-pages
env:
  global:
    # This is a convenience variable for shortening download commands
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="graalvm@19.2.0"

before_install:
  - echo "Before install"

install:
  - echo "Install"

# Original build
script:
  - echo "Script"
  - mvn --settings .travis/settings.xml clean verify -B -V -DAWS_BUCKET=${AWS_BUCKET} -DskipTests # FIXME remove skipTests

# Original deploy
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "Deploy"

after_success:
  - echo "Success"

# Special test-skipping stage to build CLI, using maven-wrapper
build-cli: &build-cli
  script:
    # re-export JAVA_HOME
    - source  ~/.jdk_config
    # Prepare everything, no settings.xml needed
    - ./mvnw clean install -B -V -DskipTests
    # Change security providers of JDK
    - /bin/bash .travis/enable_bouncycastle_security.sh
    # Build native image, no settings.xml needed
    # - ./mvnw -f datasafe-cli/pom.xml clean package -B -V -Pnative-image -DskipTests
    - /bin/bash .travis/native-image-windows.sh

# CLI artifacts publishing:
deploy-cli: &deploy-cli
  # FIXME Enabling temporary deploy rule
  deploy:
    on:
      branch: feature/datasafe-cli-w-s3
    provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${AWS_BUCKET}
    region: ${AWS_REGION}
    skip_cleanup: true
    local_dir: datasafe-cli/target
    upload-dir: datasafe-cli/${TRAVIS_OS_NAME}/${TRAVIS_COMMIT}

# Build configuration definition:
matrix:
  include:
    #### ORIGINAL BUILD ####
    # This is original build and deploy, that runs E2E tests and deploys docker images
    - os: linux
      language: java
      jdk: openjdk8

    #### CLI-ORIENTED BUILD ####
    # These are CLI-only builds that produce Datasafe cli executable for each OS:
    # CLI for Linux:
#    - os: linux
#      language: bash
#      before_install:
#        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
#      <<: *build-cli
#      <<: *deploy-cli
#    # CLI for MacOS:
#    - os: osx
#      language: bash
#      before_install:
#        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
#      <<: *build-cli
#      <<: *deploy-cli
    # CLI for Windows (disabled as of now - requires Windows SDK 7.1 and lots of other stuff):
    - os: windows
      env:
        - NO_WIN_DEFENDER=$(curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh)
      language: bash
      before_install:
        - /bin/bash .travis/install_custom_jdk_and_add_security_providers.sh
        - choco install windows-sdk-7.1
      <<: *build-cli
      <<: *deploy-cli
